audio_interface:
  bitdepth: 24
  input_device_index: 20
  output_device_index: 20
  samplerate: 44100
midi_interface:
  midi_input_name: Prophet 6 1
  midi_input_valid: true
  midi_output_name: Prophet 6 2
  midi_output_valid: true
